#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_CODIGO 10
#define MAX_PORTATEIS 30
#define MAX_STRING 50
#define MIN_ANO 2000
#define MAX_ANO 2050
#define MIN_ID 1
#define MAX_ID 99999
#define MAX_CARACTERES 999999
#endif // CONSTANTES_H_INCLUDED
